default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: mysql

development:
  database: ocrcheck_development

test:
  database: ocrcheck_test

production:
  database: ocrcheck_production