development:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DATABASE_NAME_DEVELOPMENT'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: mysql

test:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DATABASE_NAME_TEST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: r8UpCFkS
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: mysql