development:
  adapter: mysql2
  encoding: utf8
  database: ocrcheck_development
  pool: 5
  username: root
  password: <%= Rails.application.credentials.mysql[:pass] %>
  host: localhost
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: ocrcheck_test
  pool: 5
  username: root
  password: <%= Rails.application.credentials.mysql[:pass] %>
  host: localhost
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: ocrcheck_production
  pool: 5
  username: root
  password: <%= Rails.application.credentials.mysql[:pass] %>
  host: localhost
  timeout: 5000
