development:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck
  username: root
  password: rootpassword
  host: mysql

test:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck
  username: root
  password: rootpassword
  host: mysql

production:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck_production
  username: root
  password: <%= Rails.application.credentials.mysql[:pass] %>
  host: localhost
