development:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck_development
  username: root
  password: r8UpCFkS
  host: localhost

test:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck_test
  username: root
  password: r8UpCFkS
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB'] %>
  port: 3306