default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: <%= ENV['DB_USER'] %>

development:
  database: ocrcheck_development
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  database: ocrcheck_test

production:
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>