development:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck
  username: root
  password: rootpassword
  host: mysql

test:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck_test
  username: root
  password: r8UpCFkS
  host: localhost

production:
  adapter: mysql2
  encoding: utf8mb4
  database: ocrcheck
  username: root
  password: rootpassword
  host: mysql
