default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: root

development:
  database: ocrcheck_development
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  database: ocrcheck_test

production:
  <<: *default
  database: ocrcheck-db
  password: ocrcheckmysql
  host: ocrcheck-db.cr60imog2s6m.ap-northeast-1.rds.amazonaws.com
  port: 3306