name: Deploy

on:
  push:
    branches: [ feature/build-cd-pipeline ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@b256bd96bb4867e7d23e92e087d9bb697270b725
        with: 
          ruby-version: '3.3.0'

      - name: Install dependencies
        run: bundle install

      - name: Run rubocop
        run: bundle exec rubocop
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy in Amazon EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
        
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
            sudo dnf group install -y "Development Tools" &&
            sudo yum install -y ruby-devel openssl-devel libyaml-devel libffi-devel &&
            git clone https://github.com/rbenv/rbenv.git ~/.rbenv
            ~/.rbenv/bin/rbenv init &&
            TMPDIR="${PWD}/tmp" rbenv install -v 3.3.0 &&
            rbenv local 3.1.2 &&
            cd /home/naota7118/ocr_check_app &&
            git fetch --all &&
            git reset --hard origin/develop &&
            bundle install &&
            rbenv rehash &&
            lsof -t -i:3000 | xargs --no-run-if-empty kill -9 &&
            screen -dm bundle exec rails s -b 0.0.0.0
            '