name: Deploy

on:
  push:
    branches: [ feature/build-cd-pipeline ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@b256bd96bb4867e7d23e92e087d9bb697270b725
        with: 
          ruby-version: '3.3.0'

      - name: Install dependencies
        run: bundle install

      - name: Run rubocop
        run: bundle exec rubocop
  
  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Confirm SUDO_PASSWORD
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        run: |
          echo "$SUDO_PASSWORD"

      - name: Deploy in Amazon EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
        
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
            source ~/.bash_profile &&
            echo "takadanobaba" | sudo -S yum update -y && 
            echo "takadanobaba" | sudo -S dnf group install -y "Development Tools" &&
            echo "takadanobaba" | sudo -S yum install -y ruby-devel openssl-devel libyaml-devel libffi-devel &&
            echo "takadanobaba" | sudo -S dnf -y localinstall  https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm &&
            echo "takadanobaba" | sudo -S rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023 &&
            echo "takadanobaba" | sudo -S dnf install dnf-command\(mysql-devel\) &&
            echo "takadanobaba" | sudo -S dnf -y install mysql mysql-community-client &&
            echo "takadanobaba" | sudo dnf -y mysql-devel &&
            rbenv local 3.3.0 &&
            cd /home/naota7118/ocr_check_app &&
            git fetch --all &&
            git reset --hard origin/develop &&
            bundle install &&
            rbenv rehash &&
            lsof -t -i:3000 | xargs --no-run-if-empty kill -9 &&
            screen -dm bundle exec rails s -b 0.0.0.0
            '