name: Test

on:
  push:
    branched: [ feature/build-ci ]
  pull_request:
    branched: [ feature/build-ci ]

jobs:
  test:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Set up Ruby
    uses: ruby/setup-ruby@v1
    with: 
      ruby-version: '3.3.0'
  
  - name: Install dependencies
    run: bundle install

  - name: Run tests
    run: bundle exec rspec
